import { defineField, defineType } from 'sanity';

const imageWithAlt = (name = 'image') =>
  defineField({ name, type: 'image', options: { hotspot: true }, fields: [defineField({ name: 'alt', type: 'string' })] });

export const schemaTypes = [
  defineType({ name: 'artist', title: 'Artist', type: 'document', fields: [defineField({ name: 'name', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'name' } }), imageWithAlt('avatar'), imageWithAlt('bannerImage')] }),
  defineType({ name: 'genre', title: 'Genre', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } })] }),
  defineType({ name: 'track', title: 'Track', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } }), defineField({ name: 'artist', type: 'reference', to: [{ type: 'artist' }] }), defineField({ name: 'genre', type: 'reference', to: [{ type: 'genre' }] }), imageWithAlt('coverImage'), defineField({ name: 'audioPreview', type: 'url' }), defineField({ name: 'pricePerStream', type: 'number' }), defineField({ name: 'featured', type: 'boolean' }), defineField({ name: 'status', type: 'string', options: { list: ['draft', 'published'] } }), defineField({ name: 'releaseDate', type: 'datetime' })] }),
  defineType({ name: 'album', title: 'Album', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'artist', type: 'reference', to: [{ type: 'artist' }] }), defineField({ name: 'tracks', type: 'array', of: [{ type: 'reference', to: [{ type: 'track' }] }] }), imageWithAlt('coverImage')] }),
  defineType({ name: 'playlist', title: 'Playlist', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } }), defineField({ name: 'description', type: 'text' }), imageWithAlt('coverImage'), defineField({ name: 'tracks', type: 'array', of: [{ type: 'reference', to: [{ type: 'track' }] }] }), defineField({ name: 'isTrending', type: 'boolean' }), defineField({ name: 'priority', type: 'number' })] }),
  defineType({ name: 'featuredRelease', title: 'Featured Release', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'track', type: 'reference', to: [{ type: 'track' }] }), defineField({ name: 'active', type: 'boolean' })] }),
  defineType({ name: 'blogPost', title: 'Blog Post', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } }), defineField({ name: 'excerpt', type: 'text' }), defineField({ name: 'content', type: 'array', of: [{ type: 'block' }] }), imageWithAlt('coverImage'), defineField({ name: 'publishedAt', type: 'datetime' })] }),
  defineType({ name: 'announcement', title: 'Announcement', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } }), defineField({ name: 'excerpt', type: 'text' }), defineField({ name: 'content', type: 'array', of: [{ type: 'block' }] }), defineField({ name: 'active', type: 'boolean' }), defineField({ name: 'priority', type: 'number' }), defineField({ name: 'publishedAt', type: 'datetime' })] }),
  defineType({ name: 'homepageContent', title: 'Homepage Content', type: 'document', fields: [defineField({ name: 'heroTitle', type: 'string' }), defineField({ name: 'heroSubtitle', type: 'text' }), defineField({ name: 'featuredReleases', type: 'array', of: [{ type: 'reference', to: [{ type: 'track' }] }] }), defineField({ name: 'platformBanners', type: 'array', of: [{ type: 'reference', to: [{ type: 'platformBanner' }] }] })] }),
  defineType({ name: 'creatorSpotlight', title: 'Creator Spotlight', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'summary', type: 'text' }), defineField({ name: 'artist', type: 'reference', to: [{ type: 'artist' }] }), defineField({ name: 'active', type: 'boolean' }), defineField({ name: 'priority', type: 'number' })] }),
  defineType({ name: 'platformBanner', title: 'Platform Banner', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), imageWithAlt('image'), defineField({ name: 'ctaText', type: 'string' }), defineField({ name: 'ctaUrl', type: 'url' })] }),
  defineType({ name: 'faq', title: 'FAQ', type: 'document', fields: [defineField({ name: 'question', type: 'string' }), defineField({ name: 'answer', type: 'array', of: [{ type: 'block' }] })] }),
  defineType({ name: 'categoryTag', title: 'Category / Tag', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'slug', type: 'slug', options: { source: 'title' } })] }),
  defineType({ name: 'aiVocalShowcase', title: 'AI Vocal Showcase', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'track', type: 'reference', to: [{ type: 'track' }] }), defineField({ name: 'language', type: 'string' })] }),
  defineType({ name: 'remixBattle', title: 'Remix Battle', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'sourceTrack', type: 'reference', to: [{ type: 'track' }] }), defineField({ name: 'entrants', type: 'array', of: [{ type: 'reference', to: [{ type: 'track' }] }] })] }),
  defineType({ name: 'platformRecommendation', title: 'Platform Recommendation', type: 'document', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'recommendationType', type: 'string' }), defineField({ name: 'targetType', type: 'string' }), defineField({ name: 'targetRef', type: 'string' }), defineField({ name: 'payload', type: 'object' }), defineField({ name: 'priority', type: 'number' }), defineField({ name: 'active', type: 'boolean' })] }),
];
